import type { FeatureItem, RoadmapStats } from "./types";

export const FALLBACK_FEATURES: FeatureItem[] = [
  {
    id: "1",
    title: "AI Academic Assistant",
    description:
      "Intelligent support for students and lecturers on attendance, schedules, and academic queries.",
    status: "PLANNED",
    category: "AI",
    priority: "HIGH",
    beneficiary: "EVERYONE",
    estimatedRelease: "Q3 2026",
    phase: "Phase 3",
    estimatedDays: 14,
    assignedDev: "Shekinah",
    version: "2.0",
    voteCount: 342,
    commentCount: 48,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Parent Portal",
    description:
      "Allow parents to monitor student attendance and receive alerts for absences.",
    status: "PLANNED",
    category: "ADMIN",
    priority: "MEDIUM",
    beneficiary: "ADMIN",
    estimatedRelease: "Q4 2026",
    phase: "Phase 3",
    estimatedDays: 10,
    assignedDev: "Shekinah",
    version: "2.0",
    voteCount: 218,
    commentCount: 31,
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Student Mobile App",
    description:
      "Native mobile experience for attendance verification, notifications, and timetables.",
    status: "PLANNED",
    category: "MOBILE",
    priority: "HIGH",
    beneficiary: "STUDENT",
    estimatedRelease: "Q1 2027",
    phase: "Phase 4",
    estimatedDays: 30,
    assignedDev: "Shekinah",
    version: "3.0",
    voteCount: 456,
    commentCount: 62,
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Offline Attendance",
    description:
      "Record and sync attendance when internet connectivity is unavailable.",
    status: "PLANNED",
    category: "ATTENDANCE",
    priority: "MEDIUM",
    beneficiary: "LECTURER",
    estimatedRelease: "Q1 2027",
    phase: "Phase 4",
    estimatedDays: 12,
    assignedDev: "Shekinah",
    version: "3.0",
    voteCount: 189,
    commentCount: 22,
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Smart Notifications",
    description:
      "Context-aware alerts for sessions, deadlines, and attendance thresholds.",
    status: "PLANNED",
    category: "NOTIFICATIONS",
    priority: "MEDIUM",
    beneficiary: "EVERYONE",
    estimatedRelease: "Q4 2026",
    phase: "Phase 3",
    estimatedDays: 7,
    assignedDev: "Shekinah",
    version: "2.0",
    voteCount: 167,
    commentCount: 19,
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "CSV Student Import",
    description:
      "Bulk import students and lecturers from Excel/CSV with validation and error reporting.",
    status: "IN_PROGRESS",
    category: "ADMIN",
    priority: "HIGH",
    beneficiary: "ADMIN",
    estimatedRelease: "Q2 2026",
    phase: "Phase 2",
    estimatedDays: 5,
    assignedDev: "Shekinah",
    version: "1.5",
    voteCount: 127,
    commentCount: 24,
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    title: "AI Chatbot",
    description:
      "Allow users to ask questions about attendance, schedules, and reports using natural language.",
    status: "IN_PROGRESS",
    category: "AI",
    priority: "HIGH",
    beneficiary: "EVERYONE",
    estimatedRelease: "Q2 2026",
    phase: "Phase 2",
    estimatedDays: 3,
    assignedDev: "Shekinah",
    version: "2.0",
    voteCount: 289,
    commentCount: 41,
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    title: "Timetable Management",
    description:
      "Upload, manage, and display timetables for courses, groups, and lecturers.",
    status: "IN_PROGRESS",
    category: "ADMIN",
    priority: "HIGH",
    beneficiary: "ADMIN",
    estimatedRelease: "Q2 2026",
    phase: "Phase 2",
    estimatedDays: 8,
    assignedDev: "Shekinah",
    version: "1.5",
    voteCount: 203,
    commentCount: 33,
    createdAt: new Date().toISOString(),
  },
  {
    id: "9",
    title: "Attendance Reminder Emails",
    description:
      "Automated email reminders before sessions and for missed attendance verification.",
    status: "IN_PROGRESS",
    category: "NOTIFICATIONS",
    priority: "MEDIUM",
    beneficiary: "STUDENT",
    estimatedRelease: "Q2 2026",
    phase: "Phase 2",
    estimatedDays: 4,
    assignedDev: "Shekinah",
    version: "1.5",
    voteCount: 156,
    commentCount: 18,
    createdAt: new Date().toISOString(),
  },
  {
    id: "10",
    title: "QR Attendance",
    description:
      "Secure QR-based attendance verification with time-limited sessions.",
    status: "TESTING",
    category: "ATTENDANCE",
    priority: "CRITICAL",
    beneficiary: "EVERYONE",
    estimatedRelease: "Q2 2026",
    phase: "Phase 1",
    estimatedDays: 2,
    assignedDev: "Shekinah",
    version: "1.0",
    voteCount: 412,
    commentCount: 55,
    createdAt: new Date().toISOString(),
  },
  {
    id: "11",
    title: "Lecturer Attendance",
    description:
      "Track and manage lecturer attendance sessions with analytics and reporting.",
    status: "TESTING",
    category: "ATTENDANCE",
    priority: "HIGH",
    beneficiary: "LECTURER",
    estimatedRelease: "Q2 2026",
    phase: "Phase 1",
    estimatedDays: 3,
    assignedDev: "Shekinah",
    version: "1.0",
    voteCount: 178,
    commentCount: 27,
    createdAt: new Date().toISOString(),
  },
  {
    id: "12",
    title: "Missed Class Reports",
    description:
      "Students submit missed class reports; lecturers review and approve with audit trail.",
    status: "TESTING",
    category: "ATTENDANCE",
    priority: "MEDIUM",
    beneficiary: "STUDENT",
    estimatedRelease: "Q2 2026",
    phase: "Phase 1",
    estimatedDays: 4,
    assignedDev: "Shekinah",
    version: "1.0",
    voteCount: 134,
    commentCount: 21,
    createdAt: new Date().toISOString(),
  },
  {
    id: "13",
    title: "Student Registration",
    description: "Self-service and admin-driven student onboarding with role assignment.",
    status: "COMPLETED",
    category: "ADMIN",
    priority: "CRITICAL",
    beneficiary: "ADMIN",
    estimatedRelease: "Shipped",
    phase: "Phase 1",
    estimatedDays: null,
    assignedDev: "Shekinah",
    version: "1.0",
    voteCount: 98,
    commentCount: 12,
    createdAt: new Date().toISOString(),
  },
  {
    id: "14",
    title: "OTP Verification",
    description: "One-time password authentication for secure attendance verification.",
    status: "COMPLETED",
    category: "ATTENDANCE",
    priority: "CRITICAL",
    beneficiary: "STUDENT",
    estimatedRelease: "Shipped",
    phase: "Phase 1",
    estimatedDays: null,
    assignedDev: "Shekinah",
    version: "1.0",
    voteCount: 245,
    commentCount: 34,
    createdAt: new Date().toISOString(),
  },
  {
    id: "15",
    title: "Institution Management",
    description: "Multi-tenant institution setup with isolated data and configuration.",
    status: "COMPLETED",
    category: "ADMIN",
    priority: "CRITICAL",
    beneficiary: "SUPER_ADMIN",
    estimatedRelease: "Shipped",
    phase: "Phase 1",
    estimatedDays: null,
    assignedDev: "Shekinah",
    version: "1.0",
    voteCount: 112,
    commentCount: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "16",
    title: "Attendance Sessions",
    description: "Start, manage, and close live attendance sessions with real-time tracking.",
    status: "COMPLETED",
    category: "ATTENDANCE",
    priority: "CRITICAL",
    beneficiary: "LECTURER",
    estimatedRelease: "Shipped",
    phase: "Phase 1",
    estimatedDays: null,
    assignedDev: "Shekinah",
    version: "1.0",
    voteCount: 367,
    commentCount: 44,
    createdAt: new Date().toISOString(),
  },
  {
    id: "17",
    title: "Analytics Dashboard",
    description: "Real-time attendance analytics, trends, and exportable reports.",
    status: "COMPLETED",
    category: "ANALYTICS",
    priority: "HIGH",
    beneficiary: "ADMIN",
    estimatedRelease: "Shipped",
    phase: "Phase 1",
    estimatedDays: null,
    assignedDev: "Shekinah",
    version: "1.0",
    voteCount: 298,
    commentCount: 38,
    createdAt: new Date().toISOString(),
  },
  {
    id: "18",
    title: "Role-based Authentication",
    description: "Secure access control for students, lecturers, admins, and super admins.",
    status: "COMPLETED",
    category: "ADMIN",
    priority: "CRITICAL",
    beneficiary: "EVERYONE",
    estimatedRelease: "Shipped",
    phase: "Phase 1",
    estimatedDays: null,
    assignedDev: "Shekinah",
    version: "1.0",
    voteCount: 156,
    commentCount: 20,
    createdAt: new Date().toISOString(),
  },
];

export const FALLBACK_STATS: RoadmapStats = {
  featuresCompleted: 6,
  featuresPlanned: 5,
  featuresInProgress: 4,
  communitySuggestions: 24,
  totalVotes: 3847,
  institutionsUsing: 12,
  studentsManaged: 3420,
  attendanceRecords: 48000,
};
